import unittest

from forever_tools import luadata, report
from forever_tools.report import Hint, Subset

OLD = """-- Generated by x from build 1.60.1.70124. Source snapshot: 2026-09-30
local _, ns = ...
ns.A = {
	[1] = { 5, "a" },
	[2] = { 6, "b" },
}
ns.B = {
	[1] = true,
	[3] = true,
}
ns.R = {
	{ 10, "x", 100 },
	{ 11, "y", 200 },
}
"""
NEW = (
    OLD.replace('[2] = { 6, "b" },', '[2] = { 7, "b" },\n\t[4] = { 1, "d" },')
    .replace("70124", "70205")
    .replace('{ 11, "y", 200 },', '{ 11, "y", 250 },\n\t{ 12, "z", 1 },')
)
HINTS = {"ns.R": Hint(("id", "name", "cost"), key=0)}
SUBSETS = [Subset("ns.A", "ns.B", "A within B")]


class LuaDataTest(unittest.TestCase):
    def test_tables_are_read_without_running_them(self):
        tables, _ = luadata.parse_tables("ns.X = { [1] = {1, 2}, name = 'a', 'z' }")
        table = tables["ns.X"]
        self.assertEqual((table.array, table.keyed["name"], table.keyed[1].array), (["z"], "a", [1, 2]))

    def test_truncated_data_is_an_error(self):
        with self.assertRaises(luadata.LuaDataError):
            luadata.parse_tables("ns.X = { [1] = 1 ")


class ReportTest(unittest.TestCase):
    def build(self, old=OLD, new=NEW):
        return report.build_report({"Data/X.lua": (old, new)}, HINTS, SUBSETS)

    def test_records_are_keyed_not_counted_by_line(self):
        text = self.build()
        self.assertIn("`ns.A`: 2 -> 3 keyed records (+1 added, -0 removed, 1 changed)", text)
        self.assertIn("+ 4: {1, 'd'}", text)
        self.assertIn("~ 2: [1] 6 -> 7", text)
        self.assertNotIn("lines", text)

    def test_hints_name_the_changed_field(self):
        self.assertIn("~ 11: cost 200 -> 250", self.build())

    def test_builds_and_broken_references_are_reported(self):
        text = self.build()
        self.assertIn("builds: 1.60.1.70124 -> 1.60.1.70205", text)
        self.assertIn("ns.A keys missing from ns.B (A within B): 1 -> 2: 2, 4", text)

    def test_identical_data_reports_no_change(self):
        self.assertIn("No generated Lua data changed.", report.build_report({"Data/X.lua": (OLD, OLD)}, HINTS))

    def test_a_removed_file_and_mixed_builds_are_named(self):
        text = report.build_report(
            {
                "Data/A.lua": ("-- build 1.60.1.1\nns.A = {}\n", "-- build 1.60.1.1\nns.A = {}\n"),
                "Data/B.lua": ("-- build 1.60.1.1\nns.B = {}\n", "-- build 1.60.1.2\nns.B = {}\n"),
            }
        )
        self.assertIn("mixed builds of the 1.60 line", text)


if __name__ == "__main__":
    unittest.main()
